/**
* Copyright (C) 2011 Jacob Beard
* Released under GNU GPL, read the file 'COPYING' for more information
**/
define({
	DRAGGABLE : "DRAGGABLE",
	CREATOR : "CREATOR",
	ARROW_TARGET : "ARROW_TARGET",
	ARROW_SOURCE : "ARROW_SOURCE",
	DROP_TARGET : "DROP_TARGET",
	ARROW_EDITABLE : "ARROW_EDITABLE",
	CTRL_POINT_DRAG  : "CTRL_POINT_DRAG",
	TEXT_EDITABLE  : "TEXT_EDITABLE",
	RESIZABLE  : "RESIZABLE",
	SELECTABLE  : "SELECTABLE",
	REMOVABLE  : "REMOVABLE"
});
